"""Initial migration~

Revision ID: 722dd379e1fc
Revises: 
Create Date: 2023-11-28 10:49:04.430838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722dd379e1fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
